baseurl = "http://feiyoung.netlify.com"
languageCode = "en-us"
title = "Wei Liu" 
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname="Wei Liu"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
hasCJKLanguage= true
math = true
enableEmoji=true
footnotereturnlinkcontents= "↩"
rssLimit=100
[permalinks]
    en = "/:year/:month/:day/:slug/"
    cn = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "主页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "日志"
    url = "/cn/"
    weight = 2      
  
[[menu.main]]
    name = "研究"
    url = "/research/"
    weight = 3  
[[menu.main]]
    name ="诗词"
    url = "/poem/"
    weight = 4
[[menu.main]]
    name = "关于"
    url = "/cn_about/"
    weight = 5
    
[[menu.main]]
    name = "EBlog"
    url = "/en/"
    weight = 6
[[menu.main]]
    name = "About"
    url = "/en_about/"
    weight = 7  
  
    
[params]
    description = ""
    footer="&copy; [Wei Liu's HomePage](https://feiyoung.github.io/)2020| [Wei Liu's Github](https://github.com/feiyoung)"
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//weiliu.org"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//weliu.org"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "/images/me.jpg"
    width = 50
    height = 50
    alt = "Public"

