baseurl = "http://feiyoung.netlify.com"
languageCode = "en-us"
title = "Wei Liu" 
name = "Wei Liu"
theme = "hugo-Binario"
licenselink = "https://feiyoung.github.io/"
homepage = "https://feiyoung.github.io/"
googleAnalytics = ""
disqusShortname="Wei Liu"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
hasCJKLanguage= true
math = true
paginate = "12" # Number of elements per page in pagination
enableEmoji=true
footnotereturnlinkcontents= "↩"
rssLimit=100
Paginate=15 
MetaDataFormat = "toml"
PaginatePath="page"
pygmentsuseclasses = true
preserveTaxonomyNames = false
disablePathToLower =false 
enableInlineShortcodes = true
enableRobotsTXT = true


[permalinks]
    en = "/:year/:month/:day/:slug/"
    cn = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "主页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "日志"
    url = "/cn/"
    weight = 2      
  
[[menu.main]]
    name = "研究"
    url = "/research/"
    weight = 3  
[[menu.main]]
    name ="诗词"
    url = "/poem/"
    weight = 4
[[menu.main]]
    name = "笔记"
    url = "/cn_note/"
    weight = 5
    
[[menu.main]]
    name = "EBlog"
    url = "/en/"
    weight = 6
[[menu.main]]
    name = "Note"
    url = "/en_note/"
    weight = 7  
  

[taxonomies]
  category = "categories"
  tag = "tags"
  summaryLength = 250 # default 70
[params]
  hljsStyle="github" #code highlightjs css style . See [Style List](https://github.com/highlightjs/highlight.js/tree/master/src/styles "CSS Style list")

  showNextAndPrePost = true #Is Show Next and Previous Post Button
  description = "site description"
  keywords = "site keywords use seo"
  googleSiteVerification = "google site verification key"
  author = "Wei Liu"
  github ="github username"
  email="your email"
  twitter="your twitter name" 
  securityPolicy = false #disable https content security policy
  footerRight="Your tips content" #footer right content
  mainSections = ['page']
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"