---
title: "高中同学录"
author: "刘伟"
date: '2020-12-14'
output: pdf_document
layout: post
---

## 肖杨
  
花开有声，岁月无痕，三年时光转瞬即逝，但相信，回忆永恒，友谊长存，和你同桌的日子，可谓是最令我享受的，我话不多，但你整天口若悬河，讲一些不太有逻辑的笑话，而且还时不时来点小歌，你让我点歌。哎，只可惜我晓得的歌不多，不然，一定难道你。

有时，我真想把你脑袋敲开，看看你那内存是几个G的。或许，你那是浓缩的，不然那么小怎么能啥都能记住。你能告诉我，为什么你无忧无虑吗？不管何时，不管何人，你都毫不吝惜的袒露这你那稚气的微笑，叫人心情舒畅。哦，高考时你一定要给“大爷”我笑一个，算是个离别赠礼吧！还有点遗憾就是没把你那赋值法学会，我恐怕也学不会了，对了，和郭云峰比，我字咋样？小子，平时我是真人不露相，今天我也让你开开眼界！

你娃儿小小，脑袋点子多，一套赋值法被你运用的神乎其神，小至选择题大至填空题大题，都是你赋值的天堂，令兄弟不得不佩服。

朋友是一杯香醇的酒，距离拉不开思念的手，记得吗？这是我们元旦的开词，如果有机会，我们还要多来几首！

蓬山此去无多路，青鸟殷勤为探看。高考完了，咱们去大快朵颐。

签字：肖杨（当然要留一笔）地址：陈家乡跑马坪村

## 李籼珊

你一直是班上肯干，默默奉献的人。每次搬水都有你，你而且是主动去的，你的乐于奉献精神太让我羡慕了，我应该向你学习。

高三分别后，大家再见面已经几乎不可能。在这分别的时候，真心祝愿你有一个灿烂的前程，以后生活过得幸福快乐。

祝：身体健康，笑口常开，步步高升，一帆风顺。

签字：珊

## 周游

大树光辉村

乘风破浪会有时，直挂云帆济沧海。

给大爷笑一个，不笑大爷给你笑一个！

刘伟，Best Friends，快乐常伴左右。

我：从万难路经万家镇——黄都叉公路——五杆桥——你家的地图，我用文字复原回来。

签名：周游

## 李亮

舒展笑颜，天空静好。

伸开四肢，脚步沉稳。

花儿绽放，待君采撷。

草儿天青，等一烟雨。

愿你多采摘，幸福的映山红。

签名：李亮

## 郭云峰

若不能挥上一笔，岂不遗憾！

努力拼搏！

签名：郭云峰

## 蔡崴

宝剑锋从磨砺出，梅花香自苦寒来。

别忘了，我们还有一起去卖爱子奶（AIDS）哟！还要一起去乱瓣歌，
推喜欢你乱瓣的，嘿嘿。

你娃儿多努力的！

天要下雨，我要嫁人，我释笔了……

签名：蔡崴

## 蒋金超

生命的路途漫长

希望你一生的路途开满鲜花

一边是你努力拼搏绽放的成功之花

另一边是你幸福快乐浇灌的美丽之花

愿在同一片蓝天之下，你我都能到达

幸福的彼岸，彼此铭记对方

人的记忆是短暂的，总会有遗忘的，
但也有可以永存不朽的，而你我的美好回忆正是可以永存不朽的。

愿天天开心，希望过好每一个有意义的日子。

签名：蒋金超

## 李鑫龙

寄：宝剑锋从磨砺出，梅花香自苦寒来。

相信你以后的人生定会精彩多姿，生活必定幸福，愿你天天开心，心想事成……

高考即将来临，祝你在高考中得心应手，金榜题名。

签名：李鑫龙

## 阳冬东

人生路时有风雨阻，唯拼搏方能渡险关。

愿你每天都有好心情，笑口常开

勿忘我！Love you.

签名：阳冬东

## 黎秋君

天呐。你这个本至今为止全是男生！

而且这种作业本，那是相当的环保！

在一班2年，我们接触不多，但看得出你是一个正直善良的人。

所以，多么多么多么希望你能有一个光明的未来。一辈子都顺顺利利！

签名：黎秋君

## 刘超凡

黑黝黝的皮肤，腼腆而大方。看得出你内心的正直与善良，这三年来，我是你的组长，你从未漏扫偷懒，每一次班里的集体活动，你从未抗拒抵制，每一次捐款行动，你从未虚情假意，总是奉献最大的爱心。看到你，我有些惭愧，高中以来，我曾经拥有美好的东西，现在已逐渐消逝。回想这三年来的学习生活经历，自己很以你为榜样，你的存在，让我感动内心的安宁与平静。时下，你这样的人已为数不多，不管在什么时代，都需要“你”的正义感与爱心来净化社会。愿你在今后的学习生活中依然能够保持这份最伟大的人生价值，不为外物所惑。

你成绩这么好，考个好大学没问题，我听说你家住麻柳东兴，我好想去耍哦！

莫忘了，高考后收到录取通知书给我打电话呦！

祝：每时每分每秒快乐常伴左右，每年每月每日幸福总随前后

签名：刘超凡

## 王林娅

刘伟：

虽然接触不多，但是你在我心目中的印象非常好。有很多人都你很害羞，腼腆，但是我并不这样认为。虽然你平时不怎么说话，但是每当在元旦晚会上时，你就会非常大方的给我们带来幽默的、精彩的表演，这表明你也是热情的，大方的，幽默的，应该是说你属于那种该动则动，该静则静的人。而且每当看到你瘦弱的身躯却每次都积极主动地去搬水，你是多么的认真善良、诚实。而且你一直都很努力，勤奋，上进，<而这也是我所缺乏的>，所以“黄天不负有心人”，你的成绩非常棒，相信你在即将到来的高考中，金榜题名，去追逐属于自己的梦想。最后，我想说，希望你能永远保持你的善良、纯真、真挚，正所谓“出淤泥而不染，濯清涟而不妖”。中国社会正需要你这样的人。三年同窗情，是多么不舍，即将离别，道一声珍重！（字有点pie，将就将就吧！）。

愿天天开心，事事顺利

签名：王林娅

## 周梨

一起相处也快三年了，转眼我们就要各奔天涯了。真实很舍不得。

在我的印象中你一直是个勤奋刻苦，腼腆可爱，淳朴善良的小男孩。听说你想读医，相信你的聪明才智，谨慎细心，一定会开辟一条属于自己的光明大道。在你身上有许多值得我学习的品质：毅力、专心、刻苦……还没向你好好学习呢，唉，就要分别了！

祝你在几天后的高考中好好发挥，然后考一个超棒的大学，再称为你行业中的佼佼者！加油哈，以后不要忘了我哟！

Best Wishes!

签名：周梨

## 刘劼勋

刘伟同学：

同窗三年，我发觉你是个很踏实、务实的人哈！平时在学习上，你总是很积极，按照老师的要求，一步一步来。早自习能听见你使劲地读书，鼓掌！

然后我觉得你真的是个很老实的人，老实得很可爱，又喜欢帮助人家，也很活泼，真的是一个很好的人。

毕业了，也许大家见面少了，但还是要联系，同学的友谊之情永在哈！

祝：金榜题名，事业与爱情双收！

签名：刘劼勋

## 覃泽锋

满腹言语……满腹言语……唉！这么多的话怎么说，我还是别说了吧！

送你一句话，我还是喜欢你“傻傻”，这字咋写，哦“傻傻”的样子。

以后联系！暗香自幽

签名：覃泽锋

## 李梦佳

刘伟同学：

都接近三年的同学了，可没有怎么联系交流过。不过，我对你印象特别好，我觉得你是我们班人最好的男生。善良，诚恳，刻苦，向上，乐于助人……我觉得，你就像天使一样，人该拥有的品质你都占据了，这也只能让我们更加自惭形秽。

你总是微笑着面对生活，从点点滴滴中发掘快乐与幸福，你的乐观真得很感染我。我希望你能一直保持着这种达观的心态去走好未来的每一步。我相信你一定会有一个灿烂的前程！！我祝福你！

祝你笑口常开，心想事成

签名：李梦佳

最后说几句疯言疯语：

1. 每当我们起床刷牙的时候，我们的人生最纠结，一手握着“杯具”，一手握着“洗具”。

2. 问：你喜欢我哪一点？ 答：我喜欢你离我远一点。

3. 月初我吃什么狗吃什么，月末狗吃什么我吃什么。

………啊，回忆不起了！！…………


## 张依

刘伟同学啊：

你的梦想是考四川大学的医学系，我我这样体弱多病的人，以后就要找你帮我治病了哟。到时候，不准多收费哈，不是不多收费，而是不收费，耿直哟

我们班的男生，最不忍心欺负的就是你。你很老实（表面上，不晓得你内心……开玩笑）希望你以后能创出自己的一边天

你很喜欢《水手》这首歌，希望你的人生像歌中的水手一样的，一样坚强，出色，敢于拼搏。

加油哟，刘伟！

签名：张依

## 黄河滔

Dear Mr Liu:

Nice talking to you!

三年的同学了噢。first，I think. 你黑纯的，值得表扬哈。现代的社会太黑暗了，好人不多了。要继续保持哈！

衷心祝愿以后找个good wife。

<p align="right">yours </p>

<p align="right">Tao Ge！</p>

签名：黄河滔

## 崔世强

别人所说的话都只是参考，你的路到底怎样走需要你自己去决定，这个丰富的世界也需要你自己判断，再次我只能祝你好运，希望你以后的人生路能多遇见几个好人！

签名：崔世强

## 吴迪

你对学习太有激情了！真羡慕你，尤其是早自习都那么有精神，不像我，天天想睡觉。别人都说我看起来比较小，我觉得你看起来更小，而且还感觉特老实，真担心，你以后会不会被骗。不过，如果你一直是这个样子，应该没有人忍心欺负你吧，所以你不用担心啦！

祝：天天开心，顺顺利利 

To:刘伟

签名：吴迪

## 郑岚

刘伟classmate:

“他说风雨中，这点痛算什么，擦干泪不要问为什么…………”我想，你听到这首歌一定会激情澎湃吧！首先，我就将他送给你，希望他能伴你共享你的欢乐，同担你的痛苦。当然，我是希望你以后的日子里全都是快乐的身影啦！

你是一个可爱但更加诚实憨厚的人，不知不觉，在与你同学的几百个日日夜夜里，我渐渐地了解到了你是一个待人真诚而友好而又热情的人。这样的人，固然很受欢迎，但我依然会为你担心，怕你以后会被人欺负。但转念一想，应该不会有人狠心欺负你这个诚实厚道的“小同学”吧！

还有，我必须指出你一个缺点，你以后说话时可不可以快点呀！照你说话那个速度，很是让活人感到着急，知道吗？这种感觉是在6月13日晚上时被栽上火箭发射到太空中的（速度上升得太快啦）！

Best wishes for you! Day Day up!

<p align="right">Yours </p>

<p align="right">Zheng lan</p>

## 何爰龙

你咋能长这样呢？害到我每回看到你都于心不忍去欺负你。我觉得你超级老实，但sometimes超级搞笑。嗯嗯比如说你上早自习时读书，笑死我了！
（你莫嫌弃我字写的乱哈…………）

最后祝你美梦成真，发财了记得分我几千万我也不介意

用彩笔给你写希望你的人生同样多姿多彩~~

签字：何爰龙

## 王语嫣

刘伟同学：

你真是“傻”得可爱啊！傻乎乎的，却总能唤起在最心底的纯真，真的希望你能永远就这样，在复杂的社会中，就这样构建起属于自己的美丽天地，要知道，总有人喜欢你，支持你和欣赏你！你太有才了！晚会上的节目充分展现了你的高校才华，同学录的留言展现了你的文学才华，你总能让我们感到很轻松，谢谢你让我们如此快乐！加油！“海上生明月，天涯共此时”，无论在天涯海角，我都会记得我这可爱的，傻乎乎的同学！送上最美好的祝愿！

签名：王语嫣

## 杨莎

伟同学：

太不给面子了嘛，剩最后一页了。

自从见到你，世界变得好恐惧。我可不可以顺带问一下，你高中军训时是不是跟我一排的，你长得好像有一个同学哟，我来开他玩笑的。如果你是他，我跟你郑重道歉。如果你不是他，就凭长得像也帮他收下来嘛。就因为这样，我对你都是一直充满恐惧的感觉吔。

再问一下，你早自习读书nang可读成那样呢？说是读书，还来个抑扬顿挫，说是唱歌，明明是在上早自习嘛，不错，多有特色的，又避免了自己打瞌睡。

你是我见过最shy的男孩呢！shy到都不好跟你两个说话了。感觉生怕一个不小心，说错误就伤到你那幼小的心灵了，从女生的角度讲：大方一点嘛。

To：天天开心重复七次，就这样一直开心下去

签名：杨莎

日期：2011年6月2日