---
title: "随笔之阅读所感"
author: "刘伟"
date: '2021-03-07'
place: 新加坡Dorsset酒店
---

# 一、

我们一生学习的主要是：分析和解决问题的能力。无论你学习的具体内容是什么，都可归纳成这点。那为什么产生问题呢？更进一步，问题是主动产生而施加在人类或其他生物身上的？还是人类自找的问题呢？还是有的问题是主动产生，有的问题是人类自找的呢？有句俗话说：“世间本无事，庸人自扰之”，它支持问题都是人的平庸导致的自找麻烦。

我觉得有的问题是主动产生的，比如生存问题。人类花了一生的时间分出部分精力来解决该问题。这个问题是我们被动接受的，是由人类肉体的缺陷造成，若人类可不吃不喝也生龙活虎，那么生存问题也就消失了。还有的问题是人类中部分个体自找的；因为人类存在个体差异性，他们自找的问题也有差异性。有的人斤斤计较于小事，自生闷气；有的人常心怀焦虑，担忧未来；有的人羡慕别人家的孩子，而看不到自家孩子的闪光点。于是那句话可以改成“世间部分事，庸人自扰之”。

# 二、
跳出事外看事情，世间的大部分事都是小事。实际上，它们本来也就是小事，老骥伏枥回头望，鸡毛蒜皮就那样。人生的意义由我们去定义，就像周国平说的：“生活本无意义，我们在追求幸福生活的过程中产生了意义”。去想伟大的思想，去体验万物生灵之美，真正有思想和智慧的人，处处能反映出不一样的东西。

# 三、

生活才是本真，一切都是为了生活。政府说：一切为了人民；教育说：一切为了孩子；那么人民说：一切为了生活。

# 四、

太容易的事没做好，做之前不担心不焦虑；而做失败后会焦心后悔。太难的事必须去做，做之前忧心忡忡，而做完失败却感觉一身轻松，因为本来我就胜任不了的事，失败也很正常，心理也不会刁难自己。人们只会为能力附近的事而担忧，怕自己做不好，怕自己不成功。

被动发生在自己身上的不幸和坏事，也会使自己担忧难过。比如家里人生病，老师要求论文重写，主动去做而未成功的事情反而自己更容易接受，因为是自己选择的。

# 五、

对于未发生而可能发生的人祸或不幸，则自己应竭尽全力去避免和减小到最低损失，样样都接受就成了消极避世，人的主观能动性一定要发挥出来。而对于已经发生无可挽回的不幸，拿自己就要坦然接受，调整心态。当我们不能改变不幸时，就改变面对不幸的态度。

# 六、
大舅舅、大舅妈和青青姐姐闹矛盾，主要原因是不知求同存异，不知换位思考。每一方都有自己的理由来说明对方的不对，和我观点不同就是不对，老是花钱买肉吃也是不对，是不知挣钱不易，浪费钱的表现。不出去挣钱就是啥子事都不做，我挺为海洋哥心疼的，家里老是不安宁，自己心里也会难以安宁吧。

# 七、
忆往昔之不谏，知来者之可追。接纳现今好或不好的自己，知己不好而改之，知己好而励之，取人之长补己之短，以人之短警己勿犯。我们为什么常常专注于别人的缺点而忽略别人的优点，这样的人会使人人都难让你称心，越看心中越不快。而我们换成去看别人的优点，越看越舒心。

# 八、

看一个人是否爱自己，就看这个人能否长时间独处。独处，就是和自己相处，和自己相处都觉得烦躁，可见我们是多讨厌自己呀！

# 九、

创造性地工作或学习能让人感受到工作和学习的乐趣，就是多动脑子。即使很普通的工作在你的工作下变得不平凡，人对工作产生厌恶感的原因之一就是找不到工作的价值所在，感觉今天只是在重复昨天的工作，其实就是缺乏创造性工作思维，怎么用简便的方法完成这项工作？我从这项工作中能学习到什么？可行性最强的方案是什么？当你不断地动脑筋思考时，你已经开始创造性工作了，你会感受到工作的乐趣和自身的价值。

# 十、
创造性地立命和安心。

# 十一、
当学习待人不计回报，与人换位思考，寄人期望勿高，那么无人能把心扰。

# 十二、
如果将金钱平均分配，一段时间后又会达到原来的平衡状态，穷的人还是那一批人，富的人也还是那一批人。因为本质的东西未变，人的能力、见解、智慧、态度、观念、方法论等本身素质未变，不管外界怎么重新分配，最后又会达到有这些本质决定的动态平衡。

# 十三、
我觉得当今社会精而专和博而广都不适用。而应学习掌握更高的抽象能力，这种能力适用于各行各业。你的意志力、信念、思考能力、学习能力、创造能力、自信心、主观能动性、对问题的态度、心理素质、与人相处、情绪管理能力，再把这些应用于立命的专而精的工作中，任何一个工作或领域都是你这些抽象能力的实现值。

# 十四、
敢于直面自己害怕或担心的事，就像炒菜害怕用菜籽油，因为在放菜时滚烫的油会飞溅，我特别害怕溅到脸上。于是我就连续很多顿都用菜籽油炒菜，前面几次飞溅的油吓得我把菜都洒在地上，但慢慢地我就学会了用锅盖来防止溅到脸上，这样我就不害怕了，然后炒菜时就没有了恐惧心理，每次都顺利地把菜炒好了。一直坚信自己有巨大的潜能，只要认真动动脑子，遇到的问题都可以迎刃而解。