---
title: "Clustering analysis of spatial expression data"
author: "Wei Liu"
date: '2021-01-15'
---
# Markov random field
A Markov random field(MRF) is an undirected graphical model that explicitly expresses the conditional independence relationships between nodes. Two nodes are conditionally independent if all paths between them are blocked by given nodes. Thus, assume $X_i,i\in S$ is a MRF, then $X_i$ is independent of all other $X_j$ given the neighbors $N_i$ of $X_i$. 
```{Rmd}
Gassausian Graphical Model is a model frequently  explored in Statistics.
```

# Hidden markov model
Hidden Markov Model (HMM) is a statistical Markov model in which the system being modeled is assumed to be a Markov process – call it $X$ – with unobservable ("hidden") states. HMM assumes that there is another process $Y$ whose behavior "depends" on $X$. The goal is to learn about $X$ by observing $Y$.

Let $X_{n}$ and $Y_{n}$ be discrete-time stochastic processes and $n\geq 1$. The pair $(X_{n},Y_{n})$ is a hidden markov model if

1)$X_{n}$ is a Markov process whose behavior is not directly observable ("hidden");

2)$P(Y_n \in A|X_1=x_1, \cdots, X_n=x_n)=P(Y_n \in A|X_n=x_n),$
for every $n\geq 1, x_1,\cdots,x_n$ and an arbitrary (measurable) set $A$.

Terminology:
The states of the process $X_{n}$ are called hidden states, and $P(Y_n\in A|X_n=x_n)$ is called emission probability or output probability.
```{Rmd}
The process in HMM is indexed by time that is
univariant index.
```
# Hidden Markov random field
In statistics, a hidden Markov random field is a generalization of a hidden Markov model. Instead of having an underlying Markov chain, hidden Markov random fields have an underlying Markov random field.

Suppose that we observe a random field (variable) $Y_i, i\in S$. HMRFs assume that the probabilistic nature of $Y_i$ is determined by the unobservable Markov random field $X_i,i \in S$. That is, given the neighbors $N_i$ of $X_i$, $X_i$ is independent of all other $X_j$(Markov property). The main difference with a HMM is that neighborhood is not defined in 1 dimension but within a network, i.e. $X_i$ is allowed to have more than the two neighbors but a Markov chiain has no more than two. HMRF model is formulated in such a way that given $X_i, Y_i$ are independent, i.e. 
$$P(Y|X)=\Pi_{i=1}^nP(Y_i|X_i).$$ 


# Dataset web address
The first softeware  is Space Ranger, which is available at https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/what-is-space-ranger.

# Recent Method 
The recent method is called as BayesSpace available at https://edward130603.github.io/BayesSpace/articles/BayesSpace.html.

